---
version: "2.1"
services:
  openssh-server:
    image: linuxserver/openssh-server
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PUBLIC_KEY=yourpublickey #optional
      - PUBLIC_KEY_FILE=/path/to/file #optional
      - SUDO_ACCESS=false #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=tototutu #optional
      - USER_PASSWORD_FILE=/path/to/file #optional
      - USER_NAME=toto #optional
    volumes:
      - ./config:/config
    ports:
      - 2222:2222
    restart: unless-stopped


